server:
  port: 8091

spring:
  application:
    name: learn_config
  profiles:
    active: git
  cloud:
    config:
      name: cloud-config
      server:
        native:
          searchLocations: E:/githubCode/spring_cloud_learn/config_repo
        git:
          uri: https://github.com/sjian1990/spring_cloud_learn.git
          searchPaths: config_repo