server:
  port: 8097

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8092/eureka/
      
#数据库连接信息如下
spring:
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    #测试库
    url: jdbc:mysql://192.168.1.68:3306/financeAsset?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root 
    password: sjian1990
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 10
    maxActive: 200
    initialSize: 10
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false     
      
